import {
  createTheme,
  createRestyleComponent,
  createVariant,
  spacing,
  border,
  backgroundColor,
  layout,
  spacingShorthand,
} from "@shopify/restyle";
import { Platform, ViewStyle, TextStyle } from "react-native";
import { DialogWindowStyles } from "@/components/ui/modals/dialog-window/dialog-window";
const tintColorLight = "#0a7ea4";
const tintColorDark = "#fff";

export const Colors = {
  light: {
    text: "#11181C",
    background: "#fff",
    tint: tintColorLight,
    icon: "#687076",
    tabIconDefault: "#687076",
    tabIconSelected: tintColorLight,
  },
  dark: {
    text: "#ECEDEE",
    background: "#151718",
    tint: tintColorDark,
    icon: "#9BA1A6",
    tabIconDefault: "#9BA1A6",
    tabIconSelected: tintColorDark,
  },
};

export const Fonts = Platform.select({
  ios: {
    /** iOS `UIFontDescriptorSystemDesignDefault` */
    sans: "system-ui",
    /** iOS `UIFontDescriptorSystemDesignSerif` */
    serif: "ui-serif",
    /** iOS `UIFontDescriptorSystemDesignRounded` */
    rounded: "ui-rounded",
    /** iOS `UIFontDescriptorSystemDesignMonospaced` */
    mono: "ui-monospace",
  },
  default: {
    sans: "normal",
    serif: "serif",
    rounded: "normal",
    mono: "monospace",
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded:
      "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});

const createBlurStyles = (isVisible: boolean = true): ViewStyle => ({
  position: "absolute",
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  backgroundColor: "rgba(0, 0, 0, 0.5)",
  backdropFilter: Platform.select({
    web: "blur(8px)",
    default: undefined,
  }),
  display: isVisible ? "flex" : "none",
  justifyContent: "center",
  alignItems: "center",
  zIndex: 9998,
});

export const DialogWindowTheme = {
  light: {
    overlay: {
      ...createBlurStyles(true),
      ...(Platform.OS === "ios" ? {} : {}),
    } as ViewStyle,
    dialogWindowContainer: {
      marginTop: 0,
      marginBottom: 0,
      marginLeft: "auto",
      marginRight: "auto",
      position: "absolute",
      top: 0,
      bottom: 0,
      justifyContent: "center",
      alignItems: "center",
      zIndex: 9999,
      display: "flex",
      backgroundColor: "#00000000",
      width: "90%",
      padding: 6,
      alignSelf: "center",
      opacity: 1,
      transform: [{ scale: 1 }],
    } as ViewStyle,
    dialogWindowInner: {
      display: "flex",
      maxHeight: 300,
      width: "90%",
      flexDirection: "column",
      alignSelf: "center",
      gap: 6,
      borderWidth: 4,
      borderColor: "#e6e6e6",
      backgroundColor: "#ffffff",
      borderRadius: 8,
      padding: 8,
    } as ViewStyle,
    box: {
      flexDirection: "column",
      alignItems: "center",
      gap: 8,
    } as ViewStyle,
    title: {
      textAlign: "center",
      alignItems: "center",
      gap: 8,
    } as ViewStyle,
    titleText: {
      fontSize: 24,
      textAlign: "center",
      alignItems: "center",
      gap: 8,
      color: "#30C04F",
    } as TextStyle,
    description: {
      textAlign: "center",
      alignItems: "center",
    } as ViewStyle,
    descriptionText: {
      fontSize: 16,
      textAlign: "center",
      alignItems: "center",
      gap: 8,
      color: "#616161",
    } as TextStyle,
    buttonBox: {
      marginTop: 12,
      display: "flex",
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
      paddingLeft: 16,
      paddingRight: 16,
    } as ViewStyle,
    closeButton: {
      width: "100%",
      justifyContent: "center",
      alignItems: "flex-end",
      paddingTop: 2,
      paddingBottom: 2,
      paddingLeft: 12,
      paddingRight: 12,
    } as ViewStyle,
    icon: {} as ViewStyle,
    cancelButton: {
      flex: 1,
      maxWidth: 120,
      display: "flex",
      alignItems: "center",
      borderWidth: 4,
      borderColor: "#e6e6e6",
      backgroundColor: "#e6e6e6",
      borderRadius: 8,
      paddingLeft: 8,
      paddingRight: 8,
      paddingTop: 4,
      paddingBottom: 4,
    } as ViewStyle,
    cancelButtonText: {
      display: "flex",
      fontSize: 16,
      color: "#000000",
    } as TextStyle,
    successButton: {
      flex: 1,
      maxWidth: 120,
      display: "flex",
      alignItems: "center",
      borderWidth: 4,
      borderColor: "#e6e6e6",
      backgroundColor: "#e6e6e6",
      borderRadius: 8,
      paddingLeft: 8,
      paddingRight: 8,
      paddingTop: 4,
      paddingBottom: 4,
    } as ViewStyle,
    successButtonText: {
      display: "flex",
      fontSize: 16,
      color: "#000000",
    } as TextStyle,
  },
  dark: {
    overlay: {
      ...createBlurStyles(true),
      backgroundColor: "rgba(0, 0, 0, 0.7)",
    } as ViewStyle,
    dialogWindowContainer: {
      marginTop: 0,
      marginBottom: 0,
      marginLeft: "auto",
      marginRight: "auto",
      position: "absolute",
      top: 0,
      bottom: 0,
      justifyContent: "center",
      alignItems: "center",
      zIndex: 9999,
      display: "flex",
      backgroundColor: "#ffffff00",
      width: "90%",
      padding: 6,
      alignSelf: "center",
      opacity: 1,
      transform: [{ scale: 1 }],
    } as ViewStyle,
    dialogWindowInner: {
      display: "flex",
      maxHeight: 300,
      width: "90%",
      flexDirection: "column",
      alignSelf: "center",
      borderWidth: 4,
      borderColor: "#e6e6e6",
      backgroundColor: "#ffffff",
      borderRadius: 8,
      padding: 8,
    } as ViewStyle,
    box: {
      flexDirection: "column",
      alignItems: "center",
      gap: 8,
    } as ViewStyle,
    title: {
      textAlign: "center",
      alignItems: "center",
      gap: 8,
    } as ViewStyle,
    titleText: {
      fontSize: 24,
      textAlign: "center",
      alignItems: "center",
      gap: 8,
      color: "#30C04F",
    } as TextStyle,
    description: {
      textAlign: "center",
      alignItems: "center",
    } as ViewStyle,
    descriptionText: {
      fontSize: 16,
      textAlign: "center",
      alignItems: "center",
      gap: 8,
      color: "#e6e6e6",
    } as TextStyle,
    buttonBox: {
      display: "flex",
      alignItems: "center",
      flexDirection: "row",
      justifyContent: "space-between",
      paddingLeft: 16,
      paddingRight: 16,
    } as ViewStyle,
    closeButton: {
      width: "100%",
      justifyContent: "center",
      alignItems: "flex-end",
      paddingTop: 2,
      paddingBottom: 2,
      paddingLeft: 12,
      paddingRight: 12,
    } as ViewStyle,
    icon: {} as ViewStyle,
    cancelButton: {
      flex: 1,
      maxWidth: 120,
      display: "flex",
      alignItems: "center",
      borderWidth: 4,
      borderColor: "#e6e6e6",
      backgroundColor: "#e6e6e6",
      borderRadius: 8,
      paddingLeft: 8,
      paddingRight: 8,
      paddingTop: 4,
      paddingBottom: 4,
    } as ViewStyle,
    cancelButtonText: {
      display: "flex",
      fontSize: 16,
      color: "#000000",
    } as TextStyle,
    successButton: {
      flex: 1,
      maxWidth: 120,
      display: "flex",
      alignItems: "center",
      borderWidth: 4,
      borderColor: "#e6e6e6",
      backgroundColor: "#e6e6e6",
      borderRadius: 8,
      paddingLeft: 8,
      paddingRight: 8,
      paddingTop: 4,
      paddingBottom: 4,
    } as ViewStyle,
    successButtonText: {
      display: "flex",
      fontSize: 16,
      color: "#000000",
    } as TextStyle,
  },
};

export type DialogWindowThemeType = typeof DialogWindowTheme;
export type DialogWindowThemeMode = keyof typeof DialogWindowTheme;

export const ModalWindowTheme = {
  light: {
    overlay: {
      ...createBlurStyles(true),
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(0, 0, 0, 0.5)",
      justifyContent: "center",
      alignItems: "center",
      zIndex: 9998,
    } as ViewStyle,
    modalWindowContainer: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      justifyContent: "center",
      alignItems: "center",
      zIndex: 9999,
      padding: 20,
    } as ViewStyle,
    modalWindowInner: {
      backgroundColor: "#ffffff",
      borderRadius: 12,
      padding: 20,
      maxWidth: 500,
      width: "100%",
      maxHeight: "80%",
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
      position: "relative",
    } as ViewStyle,
    close: {
      position: "absolute",
      top: 10,
      right: 10,
      zIndex: 10000,
      width: 40,
      height: 40,
      justifyContent: "center",
      alignItems: "center",
      borderRadius: 20,
      backgroundColor: "rgba(0, 0, 0, 0.05)",
    } as ViewStyle,
    content: {
      width: "100%",
    } as ViewStyle,
  },
  dark: {
    overlay: {
      ...createBlurStyles(true),
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: "rgba(0, 0, 0, 0.7)",
      justifyContent: "center",
      alignItems: "center",
      zIndex: 9998,
    } as ViewStyle,
    modalWindowContainer: {
      position: "absolute",
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      justifyContent: "center",
      alignItems: "center",
      zIndex: 9999,
      padding: 20,
    } as ViewStyle,
    modalWindowInner: {
      backgroundColor: "#2a2a2a",
      borderRadius: 12,
      padding: 20,
      maxWidth: 500,
      width: "100%",
      maxHeight: "80%",
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.5,
      shadowRadius: 3.84,
      elevation: 5,
      position: "relative",
      borderWidth: 1,
      borderColor: "#404040",
    } as ViewStyle,
    close: {
      position: "absolute",
      top: 10,
      right: 10,
      zIndex: 10000,
      width: 40,
      height: 40,
      justifyContent: "center",
      alignItems: "center",
      borderRadius: 20,
      backgroundColor: "rgba(255, 255, 255, 0.1)",
    } as ViewStyle,
    content: {
      width: "100%",
    } as ViewStyle,
  },
};
export type ModalWindowThemeType = typeof ModalWindowTheme;
export type ModalWindowThemeMode = keyof typeof ModalWindowTheme;

export const DialogToastTheme = {
  light: {
    dialogToastContainer: {
      position: "absolute",
      top: 50,
      left: 20,
      right: 20,
      zIndex: 10000,
      alignItems: "center",
      pointerEvents: "box-none",
    } as ViewStyle,
    dialogToastInner: {
      backgroundColor: "#ffffff",
      borderRadius: 12,
      padding: 16,
      minWidth: 300,
      maxWidth: 400,
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
      flexDirection: "row",
      alignItems: "center",
      borderWidth: 1,
      borderColor: "#e6e6e6",
    } as ViewStyle,
    close: {
      position: "absolute",
      top: 8,
      right: 8,
      zIndex: 10001,
      width: 30,
      height: 30,
      justifyContent: "center",
      alignItems: "center",
      borderRadius: 15,
      backgroundColor: "rgba(0, 0, 0, 0.05)",
    } as ViewStyle,
    box: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    } as ViewStyle,
    icon: {
      marginRight: 8,
    } as ViewStyle,
    title: {
      flex: 1,
    } as ViewStyle,
    titleText: {
      fontSize: 16,
      fontWeight: "600",
      color: "#000000",
    } as TextStyle,
    description: {
      marginTop: 4,
    } as ViewStyle,
    descriptionText: {
      fontSize: 14,
      color: "#616161",
    } as TextStyle,
  },
  dark: {
    dialogToastContainer: {
      position: "absolute",
      top: 50,
      left: 20,
      right: 20,
      zIndex: 10000,
      alignItems: "center",
      pointerEvents: "box-none",
    } as ViewStyle,
    dialogToastInner: {
      backgroundColor: "#2a2a2a",
      borderRadius: 12,
      padding: 16,
      minWidth: 300,
      maxWidth: 400,
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.5,
      shadowRadius: 3.84,
      elevation: 5,
      flexDirection: "row",
      alignItems: "center",
      borderWidth: 1,
      borderColor: "#404040",
    } as ViewStyle,
    close: {
      position: "absolute",
      top: 8,
      right: 8,
      zIndex: 10001,
      width: 30,
      height: 30,
      justifyContent: "center",
      alignItems: "center",
      borderRadius: 15,
      backgroundColor: "rgba(255, 255, 255, 0.1)",
    } as ViewStyle,
    box: {
      flex: 1,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    } as ViewStyle,
    icon: {
      marginRight: 8,
    } as ViewStyle,
    title: {
      flex: 1,
    } as ViewStyle,
    titleText: {
      fontSize: 16,
      fontWeight: "600",
      color: "#ffffff",
    } as TextStyle,
    description: {
      marginTop: 4,
    } as ViewStyle,
    descriptionText: {
      fontSize: 14,
      color: "#e6e6e6",
    } as TextStyle,
  },
};

export type DialogToastThemeType = typeof DialogToastTheme;
export type DialogToastThemeMode = keyof typeof DialogToastTheme;
